// 라팡 품목 데이터
window.ITEMS = [
  // 과일
  { cat: "과일", name: "단감/3개", unit: "개", price: 5000 },
  { cat: "과일", name: "단감/7개", unit: "개", price: 10000 },
  { cat: "과일", name: "사과/3개", unit: "개", price: 5000 },
  { cat: "과일", name: "사과/7개", unit: "개", price: 10000 },
  { cat: "과일", name: "대봉/6개", unit: "개", price: 5000 },
  { cat: "과일", name: "대봉/13개", unit: "개", price: 10000 },
  { cat: "과일", name: "귤/9개", unit: "개", price: 3000 },
  { cat: "과일", name: "귤/20개", unit: "개", price: 6000 },
  { cat: "과일", name: "샤인/2송이", unit: "개", price: 8000 },
  { cat: "과일", name: "키위", unit: "개", price: 10000 },
  { cat: "과일", name: "석류/1개", unit: "개", price: 3500 },
  { cat: "과일", name: "석류/3개", unit: "개", price: 10000 },
  { cat: "과일", name: "바나나", unit: "개", price: 2500 },
  { cat: "과일", name: "파인애플", unit: "개", price: 4000 },
  { cat: "과일", name: "딸기/1팩", unit: "개", price: 8000 },
  { cat: "과일", name: "딸기/2팩", unit: "개", price: 15000 },
  { cat: "과일", name: "토마토", unit: "개", price: 10000 },
  { cat: "과일", name: "방울토마토/1팩", unit: "개", price: 6000 },
  { cat: "과일", name: "방울토마토/2팩", unit: "개", price: 11000 },
  { cat: "과일", name: "체리", unit: "개", price: 12000 },

  // 야채
  { cat: "야채", name: "당근", unit: "개", price: 2500 },
  { cat: "야채", name: "감자", unit: "개", price: 3000 },
  { cat: "야채", name: "고구마", unit: "개", price: 3000 },
  { cat: "야채", name: "양파", unit: "개", price: 2500 },
  { cat: "야채", name: "청양", unit: "개", price: 3000 },
  { cat: "야채", name: "아삭이", unit: "개", price: 3500 },
  { cat: "야채", name: "꽈리", unit: "개", price: 4000 },
  { cat: "야채", name: "표고", unit: "개", price: 5000 },
  { cat: "야채", name: "느타리", unit: "개", price: 2500 },
  { cat: "야채", name: "새송이/1봉", unit: "개", price: 1500 },
  { cat: "야채", name: "새송이/2봉", unit: "개", price: 2500 },
  { cat: "야채", name: "팽이/3봉", unit: "개", price: 1000 },
  { cat: "야채", name: "오이/6개", unit: "개", price: 3000 },
  { cat: "야채", name: "가지/4개", unit: "개", price: 3000 },
  { cat: "야채", name: "애호박/3개", unit: "개", price: 3500 },
  { cat: "야채", name: "브로콜리/1개", unit: "개", price: 1300 },
  { cat: "야채", name: "브로콜리/3개", unit: "개", price: 3000 },
  { cat: "야채", name: "샐러리", unit: "개", price: 2000 },
  { cat: "야채", name: "미나리", unit: "개", price: 3000 },
  { cat: "야채", name: "우엉", unit: "개", price: 3000 },
  { cat: "야채", name: "연근", unit: "개", price: 3000 },
  { cat: "야채", name: "더덕", unit: "개", price: 6000 },
  { cat: "야채", name: "알배기", unit: "개", price: 5000 },
  { cat: "야채", name: "양배추", unit: "개", price: 2000 },
  { cat: "야채", name: "양상추", unit: "개", price: 1500 },
  { cat: "야채", name: "대파", unit: "개", price: 1000 },
  { cat: "야채", name: "쪽파", unit: "개", price: 4000 },
  { cat: "야채", name: "부추", unit: "개", price: 2000 },
  { cat: "야채", name: "무", unit: "개", price: 1500 },
  { cat: "야채", name: "마늘/작은", unit: "개", price: 1500 },
  { cat: "야채", name: "마늘/큰마늘", unit: "개", price: 5000 },

  // 잎채소
  { cat: "잎채소", name: "시금치/1봉지", unit: "개", price: 2000 },
  { cat: "잎채소", name: "시금치/1단", unit: "개", price: 1500 },
  { cat: "잎채소", name: "상추", unit: "개", price: 1000 },
  { cat: "잎채소", name: "깻잎", unit: "개", price: 1000 },
  { cat: "잎채소", name: "콩나물", unit: "개", price: 500 },
  { cat: "잎채소", name: "숙주", unit: "개", price: 1000 },
  { cat: "잎채소", name: "청경채", unit: "개", price: 1000 },
  { cat: "잎채소", name: "케일", unit: "개", price: 1000 },
  { cat: "잎채소", name: "치커리", unit: "개", price: 1000 },
  { cat: "잎채소", name: "적겨자", unit: "개", price: 1000 },
  { cat: "잎채소", name: "근대", unit: "개", price: 1000 },
  { cat: "잎채소", name: "아욱", unit: "개", price: 1500 },
  { cat: "잎채소", name: "고추잎", unit: "개", price: 2000 },
  { cat: "잎채소", name: "쑥갓", unit: "개", price: 1500 },
  { cat: "잎채소", name: "참나물", unit: "개", price: 1500 },
  { cat: "잎채소", name: "취나물", unit: "개", price: 2000 },

  // 생선
  { cat: "생선", name: "동태/1마리", unit: "개", price: 3000 },
  { cat: "생선", name: "동태/2마리", unit: "개", price: 5000 },
  { cat: "생선", name: "오징어/1마리", unit: "개", price: 3000 },
  { cat: "생선", name: "오징어/2마리", unit: "개", price: 5000 },
  { cat: "생선", name: "꼬막/1망", unit: "개", price: 3000 },
  { cat: "생선", name: "꼬막/2망", unit: "개", price: 5000 },
  { cat: "생선", name: "코다리/1코", unit: "개", price: 8000 },
  { cat: "생선", name: "코다리/2코", unit: "개", price: 15000 },
  { cat: "생선", name: "갈치", unit: "개", price: 7000 },
  { cat: "생선", name: "굴비", unit: "개", price: 10000 },
  { cat: "생선", name: "번데기/1봉", unit: "개", price: 3000 },
  { cat: "생선", name: "번데기/2봉", unit: "개", price: 5000 },
  { cat: "생선", name: "굴/1봉", unit: "개", price: 3000 },
  { cat: "생선", name: "굴/2봉", unit: "개", price: 5000 },
  { cat: "생선", name: "동태포/1팩", unit: "개", price: 3000 },
  { cat: "생선", name: "동태포/2팩", unit: "개", price: 5000 },
  { cat: "생선", name: "낀따로", unit: "개", price: 5000 },
  { cat: "생선", name: "삼치", unit: "개", price: 5000 },
  { cat: "생선", name: "고등어/1마리", unit: "개", price: 3500 },
  { cat: "생선", name: "고등어/3마리", unit: "개", price: 10000 },
  { cat: "생선", name: "자반", unit: "개", price: 6000 },
];
